import math
print("==============================")
print("        CALCULATOR            ")
print("==============================")
n1 = int(input("Number 1: "))
n2 = int(input("Number 2: "))
print("Addition :", n1+n2)
print("Subtraction: ", n1-n2)
print("Multiplication: ", n1*n2)
print("Division: ", n1/n2)
print("Floor division: ", math.floor(n1/n2))
print("Remainder: ", n1%n2)
print("Power: ", math.pow(n1,n2))
print("==============================")
