print("Welcome to the tip calculator?")
print("What is the total bill amount?")
bill = float(input("$: "))
print("How much tip would you like to give?")
tip = float(input("Percent:"))
print("How many people to split the bill")
people = float(input("People:"))
pay = bill + bill*(tip/100)
print("Each person have to pay $", {pay/people})
